### ISSUE TITLE
Low performance (slow computation) when history is very long

### ISSUE THREAD

**Issue by hsandt** [speedcrunch/SpeedCrunch#101]
I recently noticed that my SpeedCrunch was become slower and slower. Since it happened gradually over time, I suspected my long history to be the culprit. So I cleared it with Edit > Clear History. And now it's super fast again!

That means that the slowness didn't come from the computation itself, but rather adding a entry to a very long queue/stack and displaying it. I saw this happen in a few other apps too. Maybe when we reach a very huge value, the container resize requires memory reallocation or something...

Should we fix this by improving the way history is stored? Or allowing user to set a max history size, with some reasonable default?

**Comment by heldercorreia** [comment]
Hi.  GH hasn't been used for a long while.  See https://bitbucket.org/heldercorreia/speedcrunch/issues/746/very-slow-when-history-gets-large

**Comment by hsandt** [comment]
Thx, closing this one.
