### ISSUE TITLE
new release before the end of the year?

### ISSUE THREAD

**Issue by excalibur1234** [speedcrunch/SpeedCrunch#60]
the latest official release of speedcrunch is version 0.11. it is still based on qt4.
if i remember correctly, qt4 is only supported until the end of the year. 
the latest git version of speedcrunch already works nicely with qt5.

can you release a new (qt5) version until the end of the year?

**Comment by heldercorreia** [comment]
No promises. But yes, I realy hope a new release can come before the end of the year. Finishing the new fetures/bug features is one thing, but I also depend on other people who build the Windows and OS X packages, who have busy lives like mine.
