### ISSUE TITLE
Custom function definitions

### ISSUE THREAD

**Issue by crdx** [speedcrunch/SpeedCrunch#61]
Has any work been done so far on allowing custom functions?

I'm looking for a PowerToy Calc replacement and this meets the requirements and far beyond, except for one thing: I can't define my own functions. In PowerToy Calc it's done by entering a statement such as `f(x) = x*2` and then from then on `f()` becomes a callable function taking a single parameter. 

I'm interested in this feature enough that I would spend time implementing it myself but I thought I'd ask first to make sure efforts aren't duplicated.

**Comment by heldercorreia** [comment]
The feature has been in master branch for a year now. See https://code.google.com/p/speedcrunch/issues/detail?id=38
