### ISSUE TITLE
Decimal separator in binary

### ISSUE THREAD

**Issue by flip111** [speedcrunch/SpeedCrunch#98]
It would be nice to have the decimal separator available for binary notation.

Example: `0b0.1` = `0.5`

This is important for fixed point calculations.

**Comment by Tey** [comment]
It's already available in the dev branch. You can download development builds ([Windows](https://github.com/Tey/speedcrunch-nightlies/releases) or [Linux/Ubuntu](https://code.launchpad.net/~fkrull/+archive/ubuntu/speedcrunch-daily)) if you want to use it now or wait for the "coming soon" release.

Also, please note the project moved to [bitbucket](https://bitbucket.org/heldercorreia/speedcrunch/) now.

**Comment by flip111** [comment]
Alright, thank you!
